### ISSUE TITLE
Remote mode doesn't work on MS Basic Optical Mouse v2.0

### ISSUE THREAD

**Issue by necroware** [necroware/ps2-serial-mouse-adapter#2]
Some MS Basic Optical Mouse v2.0 seem to have problems in remote mode. The mouse seem to need explicit enable data reporting command. The mouse seems to work flawlessly in streaming mode however, where the command will already be sent. There were reports with the same mouse already working without this issue, but MS seems to have different guts in mice released under the same name. On problematic devices the adapter doesn't seem to receive any data from the mouse and the optical sensor on the mouse remains dark.

**Comment by appiah4** [comment]
I have tested pull request code ps2-serial-mouse-adapter-fix-remote-mode and I can confirm that it worked flawlessly with the problematic MS USB Basic Optimal Mouse 2.0.

It also changed the behavior of another problematic mouse, the A4Tech OP-720 Optical PS/2:
+When connected to the Arduino IDE the mouse now reports proper initialization on Serial Monitor (Previously would get stuck at "Reseting PS/2 mouse"
+When connected to a retro pc the mouse driver detects a mouse at COM1 and loads into memory but there is no cursor movement

This behavior is the same for normal and streaming mode.
